### ISSUE TITLE
Handle .eslintrc comma dangles?

### ISSUE THREAD

**Issue by stela5** [MiguelCastillo/Brackets-InteractiveLinter#169]
The interactive linter was complaining with an Aurelia project and I tracked it down to a dangling comma in the *.eslintrc* file: https://github.com/aurelia/skeleton-navigation/blob/master/.eslintrc#L4

Any thoughts for supporting it?  http://eslint.org/docs/rules/comma-dangle.html

**Comment by MiguelCastillo** [comment]
@stela5 FYI - dangling commas will cause problems in IE.  I am not sure what versions anymore but that was definitely an issue.

As far as interactive linter goes.  the fact that it complained about it makes me happy :)  It is catching problems and telling you about it.  Also, interactive linter uses https://github.com/zaach/jsonlint to do the JSON linting, so that wouldn't be an ESLint that complained about your .eslintrc file.  And I am not sure you turn off that behavior.

The eslint setting is for for javascript files...  And I would not recommend ignoring those warnings/errors. :)

**Comment by stela5** [comment]
Okay, thanks!
